### ISSUE TITLE
Crate only works on Raspberry Pi

### ISSUE THREAD

**Issue by brocaar** [DASPRiD/aw2013#1]
First of all thanks for your work to create a crate for the aw2013 led controller :) I noticed this crate only works on Raspberry Pi targets due to the `rppal` dependency (I get this error: https://docs.golemparts.com/rppal/0.16.1/rppal/i2c/enum.Error.html#variant.UnknownModel). Would you be interested in a pull-request to make this Linux compatible rather than Raspberry Pi only (using the `linux-embedded-hal` crate instead of `rpal`)? 

For a project I'm working on, I already made these changes and I would be happy to prepare a PR for these changes.

**Comment by DASPRiD** [comment]
Sure, sounds like a great improvement :)

**Comment by DASPRiD** [comment]
Actually, it might make even more sense to use `embedded-hal` as dependency, then this could be made to work in `no-std` environments as well. This actually should be a small change, lemme see if I can get that together in the next hour :)

**Comment by DASPRiD** [comment]
Do you see any harm with going embedded-hal 1.0 only? It seems like any hal implementation out there does support it for a while now.

**Comment by brocaar** [comment]
Thanks @DASPRiD, I proposed `linux-embedded-hal` as that way the API would stay the same, but I agree this is a better and more flexible solution :+1:

**Comment by DASPRiD** [comment]
What a timing, embedded hal 1 final was released today 😅
